model_list:
  - model_name: claude-sonnet-4-6
    litellm_params:
      model: anthropic/claude-sonnet-4-6
      api_key: os.environ/ANTHROPIC_API_KEY
      api_base: os.environ/ANTHROPIC_BASE_URL
  - model_name: claude-opus-4-6
    litellm_params:
      model: anthropic/claude-opus-4-6
      api_key: os.environ/ANTHROPIC_API_KEY
      api_base: os.environ/ANTHROPIC_BASE_URL
litellm_settings:
  drop_params: true

general_settings:
  disable_end_user_cost_tracking: true
  enable_jwt_auth: false
  enforce_user_param: false
  allow_user_auth: false
  master_key: null
